### ISSUE TITLE
语音按钮的UIControlEventTouchDown事件为什么在我的项目里不能调用呢？

### ISSUE THREAD

**Issue by vanwang** [ZhipingYang/UUChatTableView#13]
我在使用呢UUChatTableView的时候，语音按钮长按录音不能用，其他功能正常，发现是UIControlEventTouchDown事件没有监听到，不知道是什么原因，请问你知道吗？
[self.btnVoiceRecord addTarget:self action:@selector(beginRecordVoice:) forControlEvents:UIControlEventTouchDown];

**Comment by ZhipingYang** [comment]
？？？不是原来就有touchDown方法？你要添加一个touchDown新事件？？

**Comment by G1King** [comment]
touchDown 延迟响应
