### ISSUE TITLE
请教一些问题，关于qq表情

### ISSUE THREAD

**Issue by redstaryan** [ZhipingYang/UUChatTableView#14]
请问怎么添加qq表情

**Comment by ZhipingYang** [comment]
那要自己自定义添加一个表情键盘。系统自带表情包含在字符串中。自定义表情键盘需要定制attributeSting，太麻烦我就给忽略。
可以参考：https://github.com/xhzengAIB/MessageDisplayKit
或者：https://github.com/jessesquires/JSQMessagesViewController
