### ISSUE TITLE
关于UUInputFunctionView导入我的工程不出现了，但是自己新建工程可以我很奇怪

### ISSUE THREAD

**Issue by laizhouzhang** [ZhipingYang/UUChatTableView#16]
关于UUInputFunctionView导入我的工程不出现了，但是自己新建工程可以我很奇怪

**Comment by ZhipingYang** [comment]
你可以试一试Xcode的

View UI Hierarcy

或者使用reveal查看界面布局也可以，

应该是有的，只是可能导航栏不透明等等原因造成位置偏移。

**Comment by laizhouzhang** [comment]
非常感谢很好的工具，请问UUInputFunctionView怎么会变成了很底部，怎么把它调整回来
