### ISSUE TITLE
请问getDic下，从服务端接收语音消息应该怎么处理

### ISSUE THREAD

**Issue by laizhouzhang** [ZhipingYang/UUChatTableView#18]
demo貌似没有对对方发送的语音进行处理,不能播放。ERror creating player: Error Domain=NSOSStatusErrorDomain Code=1954115647 "The operation couldn’t be completed. (OSStatus error 1954115647.)"只有自己发送的语音才有。

**Comment by ZhipingYang** [comment]
自己和对方发送的语音都是从网络获取的，demo只是模拟本地数据。播放单例里可以简单看看，使用前最好全局了解一下框架，播放单例里也有网络请求语音方法

**Comment by laizhouzhang** [comment]
哦哦，谢谢，貌似只能播放caf的文件？

**Comment by ZhipingYang** [comment]
不是啊，我使用的语音库可以装换成MP3格式，这样可以跨平台
