### ISSUE TITLE
没有用xib 布局 求指导

### ISSUE THREAD

**Issue by juntity** [ZhipingYang/UUChatTableView#19]
我没有用xib布局  我想问下  那个NSLayoutConstraint *bottomConstraint 这个应该怎么去写呢

**Comment by ZhipingYang** [comment]
那你是用StoryBoard？是的话改动不大，要是使用代码的autolayout，也是可以的。
都不是就只能代码手动修改控件的frame。为什么不使用xib或其他的？？
