### ISSUE TITLE
请问怎么样保存住自己之前发送的的文字或语音，现在不能保存。

### ISSUE THREAD

**Issue by laizhouzhang** [ZhipingYang/UUChatTableView#22]
请问怎么样保存住自己之前发送的的文字或语音，现在不能保存

**Comment by ZhipingYang** [comment]
你是说做本地缓存？要做的话，简单实现推荐你使用[EGOCache](https://github.com/enormego/EGOCache)

**Comment by ZhipingYang** [comment]
如果有时间，我会去加上缓存功能的。
