### ISSUE TITLE
发送完消息，点击空白处收起键盘有个bug

### ISSUE THREAD

**Issue by xushichen** [ZhipingYang/UUChatTableView#24]
发送完消息，点击空白处收起键盘有个bug,键盘收起 消息cell会有个插入的动画。

**Comment by ZhipingYang** [comment]
你的意思是，插入动画是bug？还是插入动画造成UI布局错误？

**Comment by xushichen** [comment]
是个bug 虽然不会影响布局 但是这个用户体验并不理想，你可以多试几次。

**Comment by ZhipingYang** [comment]
这个应该无法避免吧，有键盘时不停输入多个消息后cell重用个数比较小，等键盘回去后，可视空间变大cell就会被alloc，产生向左插入的电话，但其实也不明显，感觉还好。
by the way, 你好仔细啊。。。

**Comment by xushichen** [comment]
哈哈 我比较喜欢体验产品。在看到这个问题的时候我有试着去修改，但是并不理想。所以想请教你一下哈。
