### ISSUE TITLE
请问下图片怎么实现异步加载啊

### ISSUE THREAD

**Issue by njlcazl** [ZhipingYang/UUChatTableView#26]
点进聊天界面会卡住。

**Comment by ZhipingYang** [comment]
你好，我使用的时 UIKit+AFNetworking 它本事就是AFNetworking的一个拓展，异步的。
你是说界面进入加载时卡顿还是滑动时卡顿？

**Comment by njlcazl** [comment]
比如在会话界面，用户收到一张图片，想点进聊天界面查看，但是要等到图片从服务器上下载并加载完成以后才能够进入聊天界面，这个怎么解决

**Comment by njlcazl** [comment]
- (UUMessageFrame *)addMsg:(UCSMessage *)MsgItem这个方法中dictionary的setObject是直接传一个UIImage进去的，这个不是异步加载啊

**Comment by ZhipingYang** [comment]
兄弟啊，那是一个Demo，不是最终项目实战的样子。你应该使用URLString传给cell，在cell中让imageview异步加载图片。我只是简化写一个本地Demo而已

**Comment by ZhipingYang** [comment]
[查看这里](https://github.com/ZhipingYang/UUChatTableView/blob/master/Demo/UUChat/UUMessageCell.m#L215)把image赋值改用UIkit+AFNetworking 或者 SDWebimage都可以啊。

**Comment by njlcazl** [comment]
成功了。谢谢你啊
