### ISSUE TITLE
加qq573979861

### ISSUE THREAD

**Issue by xushichen** [ZhipingYang/UUChatTableView#3]
加qq573979861

**Comment by ZhipingYang** [comment]
:smiley: 哪里不懂可以直接说的。qq比较少用。

**Comment by xushichen** [comment]
对话框的frame不能调吗 找了好久没找到 只看到拉伸的函数＝＝

**Comment by ZhipingYang** [comment]
对话框是指气泡吗？气泡frame的大小在cellFrame类里设置的。但是气泡里面的语音和图片frame在UUMessageContentButton类里

**Comment by xushichen** [comment]
找到了 谢谢，只是没有自定义的表情键盘，少了那么一点东西
