### ISSUE TITLE
我移植了demo到另外一个project上面navigationbar 和keyboard出现问题

### ISSUE THREAD

**Issue by klient92** [ZhipingYang/UUChatTableView#32]
移植之后navigationbar和statusbar变大 键盘也多了一行done，在弹出对话框的时候navigationbar会上移 请问是怎么回事啊

**Comment by ZhipingYang** [comment]
你用了第三方库来辅助键盘输入吧。比如IQKeyBoardManger之类的

**Comment by ZhipingYang** [comment]
存在inputAccessoryView可能
