### ISSUE TITLE
实现聊天功能

### ISSUE THREAD

**Issue by 18612117463** [ZhipingYang/UUChatTableView#38]
博主您好，如果实现两个人聊天，怎么把系统自动出现的聊天消息换成真实用户发送过来的消息啊？

**Comment by XavierXia** [comment]
你可以着重看一下 ChatModel.m；
把随机加载数据源的地方（- (void)addRandomItemsToDataSource:(NSInteger)number）改成从真实用户信息即可；推送过来的 真实用户数据可以存在数据库中，然后显示时再从数据库中取到；

**Comment by 18612117463** [comment]
方便加一下您的QQ吗？或者是您加我，这里还是搞不明白。QQ：412499326
