### ISSUE TITLE
How to use in storyboard

### ISSUE THREAD

**Issue by nishanth9493** [ZhipingYang/UUChatTableView#55]
I copied all the files in my project.
the cells are getting resized but no data or the chat bubbles are being displayed. kindly help me

**Comment by ZhipingYang** [comment]
I need to check the bubbles images been copied in your project.

**Comment by nishanth9493** [comment]
I mean like how to detect links, phonenumbers etc. can i use Textview instead of button

**Comment by nishanth9493** [comment]
It was a small mistake from my side. thanks for your support
