### ISSUE TITLE
新的方案

### ISSUE THREAD

**Issue by ghost** [ZhipingYang/UUChatTableView#61]
其实有个新的方案来做聊天列表的，我看gitHub主把系统时间消息和文本消息等一起做到一个cell里面去了，其实以后的代码耦合度是很高的，一旦新的功能拓展，例如需要添加类似qq的警告信息("陌生好友添加请注意安全")这些消息，可能又要放到一个cell去做，久而久之，cell的文件的代码量可想而知，

班门弄斧一下，其实github主可以选择把cell抽离出来写，例如Message消息一个cell，系统提示消息一个cell，and其他的cell。每个cell对应着不同的model。这样就会清晰很多了。处理的时候。model传给cell。由cell来处理不同的数据源

**Comment by ZhipingYang** [comment]
你说的是，这个其实是很简易的IM；确实是很有必要添加系统消息的cell；有一点我不大明白，你是想把时间剥离出来做个cell还是？

**Comment by mgoofyy** [comment]
剥离出来分成cell 和model。解耦嘛

**Comment by ZhipingYang** [comment]
# ⚠️ Mark  
太久没有更新了，维持一个基础的UI框架就好了😅，后续自定义的功能可以自己再添加。比如你说的时间、系统消息等等是应该独立于left、right气泡cell的。有时间再改进框架，改成用通用的left/center/right，内容view遵守一个size计算协议就好了。这样视频、地图等等都可以直接使用了，不限制内容了。
