### ISSUE TITLE
有纯代码的吗

### ISSUE THREAD

**Issue by Panshuyan** [ZhipingYang/UUChatTableView#62]
扔到我的项目中一推错误，都没有心情改了！
@property (strong, nonatomic)  NSLayoutConstraint *bottomConstraint; // 底部的约束
改成这样，发信息的框都没有显示

**Comment by ZhipingYang** [comment]
哈哈，你引入的NSLayoutConstraint *bottomConstraint需要通过xib加进去。恩，做的Demo当时图个方便，会改的

**Comment by ZhipingYang** [comment]
去除xib了
