### ISSUE TITLE
底部输入工具栏不显示

### ISSUE THREAD

**Issue by ReadyFlyStone** [ZhipingYang/UUChatTableView#63]
你好,在按照demo创建聊天界面的时候底部输入工具栏不能显示,这会和xib没有设置好有关系吗?

**Comment by ZhipingYang** [comment]
修改一下底部的约束就可以了。😭，我还没有去更新

**Comment by ReadyFlyStone** [comment]
不好意思，这么晚才回你。我是自己做了一个navigationCV的基类，修改了view的坐标，所以下移了64，后来才想到。😂😂😂


在2016年11月14日 11:17，Zhiping Yang 写道:

修改一下底部的约束就可以了。😭，我还没有去更新
