### ISSUE TITLE
请问如何只把输入框抽取出来

### ISSUE THREAD

**Issue by 513494297** [ZhipingYang/UUChatTableView#65]

**Comment by ZhipingYang** [comment]
?

**Comment by 513494297** [comment]
底层的toolsbar效果很棒，可是我水平有限，无法把它单独剥离出来用到我的项目中

**Comment by ZhipingYang** [comment]
那是试试粗暴的把左右按钮隐藏，中间输入框放大试试。剥离其实也不会很麻烦的

**Comment by ZhipingYang** [comment]
你主要需要的效果应该就是和键盘的响应吧。

[查看这个实现就好了](https://github.com/ZhipingYang/UUChatTableView/blob/master/Demo/UUChatTableView/RootViewController.m#L155)
