### ISSUE TITLE
底部输入框位置问题

### ISSUE THREAD

**Issue by ChenTF** [ZhipingYang/UUChatTableView#7]
当我从RootVC push 到别的页面, 在别的页面有个UITextField, 然后点击弹出输入键盘, 这时候pop 回RootVC则底部的输入框的位置将不正确, 将显示在聊天tableview上方, 并且没有键盘.

**Comment by ZhipingYang** [comment]
都是通知惹的祸啊。
试一试解决方案
方法一：
你在ChatVC的viewWillAppear的方法里加上[self.view endEditing:YES];
方案二：
在pop时加上[self.view endEditing:YES]；

主要原因是：键盘通知都是接受于window发出的，没有做过滤筛选。改天加上

**Comment by ChenTF** [comment]
这两个方案都违反了类设计原则."自己的事情自己处理". 
我刚修复好, 在UUInputFunctionView 的 keyboardDidShowOrHide方法修改如下:
...
...
    CGRect newFrame = self.frame;
    newFrame.origin.y = keyboardEndFrame.origin.y - newFrame.size.height;
    self.frame = newFrame;
    
    // 当别的页面有textField编辑状态返回时进入
    CGRect keyboardBeginFrame;
    [[userInfo objectForKey:UIKeyboardFrameBeginUserInfoKey] getValue:&keyboardBeginFrame];
    if (CGRectEqualToRect(keyboardBeginFrame, keyboardEndFrame)) {
        // 修复frame 位置不正确
        CGFloat VCWidth = Main_Screen_Width;
        CGFloat VCHeight = Main_Screen_Height;
        CGRect frame = CGRectMake(0, VCHeight-40, VCWidth, 40);
        self.frame = frame;
    }
    
    [UIView commitAnimations];

**Comment by ChenTF** [comment]
对通知进行筛选? 
我刚开始试着进行筛选, 没有成功.
如果你改进后还麻烦告诉我下, 我学学如何进行筛选.

学习学习.😊

**Comment by ZhipingYang** [comment]
window发出的keyboard通知不好整。
但是还是修复好bug了。可以去下载新的Demo

筛选就通知的object，谁发送的object就是谁，筛选适合自定义通知，系统的我也不大会 啊。目前不知道有什么好的方法，只能先将就了

**Comment by ZhipingYang** [comment]
我看了你的解决方案，大侠，我表示有点不明白你的意思。
我尝试够self.view.window != nil 时表示当前VC再做布局，但是还是有缺点。
最后解决方法就是进来添加观察者，跳转后就移除观察者

**Comment by ChenTF** [comment]
我的那个解决方案是分析 第二个VC 执行pop效果时keyboardBeginFrame 与 keyboardEndFrame一致得出的.  
正常情况你之前写的是没有问题的, 但是在编辑状态pop时两个frame居然是一致的!!  理论上EndFrame应该是屏幕的高度. 我估计是系统为了节省资源进行了处理, 所以我用那种方法来进行判断, 改正, 就可以了.

这种方法我现在还不知道会有什么隐患, 如果有什么问题的话请指出.
