### ISSUE TITLE
请问，为什么从服务器返回图片的时候会崩溃

### ISSUE THREAD

**Issue by 970569524** [ZhipingYang/UUChatTableView#70]
-[__NSCFConstantString size]: unrecognized selector sent to instance 0x103af2218

我看你这边都是写死的
case UUMessageTypePicture:
            contentSize = CGSizeMake(ChatPicWH, ChatPicWH);

要怎么相关处理呢，谢谢

**Comment by ZhipingYang** [comment]
这没有问题啊，你这错误日志是未找到对象方法。检查一下代码

**Comment by 970569524** [comment]
加载服务器返回的图片是不是还要另外处理呢，这个demo只能加载 本地图片吗

**Comment by 970569524** [comment]
加载服务器返回的图片是不是还要另外处理呢，这个demo只能加载 本地图片吗

**Comment by ZhipingYang** [comment]
肯定啊，demo只是demo，插件化API设计还没有做完（最近有闲置了一段时间），你在cell的方法里面修改一个，model也要和你们公司字段相匹配。

**Comment by 970569524** [comment]
好的，谢谢

**Comment by 970569524** [comment]
好的，谢谢
