### ISSUE TITLE
发送接收数据

### ISSUE THREAD

**Issue by ZachGuoMingyu** [ZhipingYang/UUChatTableView#71]
作者您好，我是一个iOS小白，最近需要用到这个框架，我想问一下，发送数据和接收数据分别在哪里处理？

**Comment by ZhipingYang** [comment]
addSpecifiedItem
> 添加自己的数据，同理添加别人的聊天内容也可以。只是`[dataDic setObject:@(UUMessageFromMe) forKey:@"from"];`给成别人的

https://github.com/ZhipingYang/UUChatTableView/blob/master/Demo/UUChatTableView/ChatModel.m#L36

**Comment by ZachGuoMingyu** [comment]
如果说我需要保存聊天记录到服务器，再次获取的时候是不是需要做一个判断，判断是别人发的还是我发的，然后显示出来，这个判断需要在哪里执行呢？

**Comment by ZachGuoMingyu** [comment]
addSpecifiedItem:我是不是可以再写一个这个方法 添加别人的item

**Comment by ZhipingYang** [comment]
改from字段就可以了

**Comment by ZachGuoMingyu** [comment]
其实我现在的问题就是发送数据可以发送，但是他人发的数据我不知道怎么显示，因为刚刚接触iOS不久，有的地方还是理解不了，多次麻烦您，非常感谢
