### ISSUE TITLE
VoiceLib找到了么?

### ISSUE THREAD

**Issue by MRZHL** [ZhipingYang/UUChatTableView#72]

**Comment by MRZHL** [comment]
接着前同事的项目,前同事把项目用SVN 提交忽略了很多.a 的库, 有一个就是UUChat

**Comment by ZhipingYang** [comment]
😂 找不到，我自己都快放弃了。
demo暂时不用voiceLib了，使用原生的AVFoundation处理。和Android平台互通最好是MP3，你可以看看有没有适合的语音库可以接入，或者其他的解决方案。
