### ISSUE TITLE
你好，我自定义表情键盘然后发送图片就会出现如下图的问题

### ISSUE THREAD

**Issue by xiaobeifeng** [ZhipingYang/UUChatTableView#73]
![image.png](https://upload-images.jianshu.io/upload_images/1685769-9856ef4972c0cefe.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

我在 UUMessageCell.m 中，对收到的文本消息进行富文本处理就会这样，希望作者可以解答下，感谢
```
 case UUMessageTypeText:
        {
            NSMutableAttributedString *attributedMessage = [[NSMutableAttributedString alloc] initWithString:message.strContent attributes:@{ NSFontAttributeName: [UIFont systemFontOfSize:14.0], NSForegroundColorAttributeName: [UIColor lightGrayColor] }];
            [PPStickerDataManager.sharedInstance replaceEmojiForAttributedString:attributedMessage font:[UIFont systemFontOfSize:14.0]];
            
            [self.btnContent setAttributedTitle:attributedMessage forState:UIControlStateNormal];
//            [self.btnContent setTitle:message.strContent forState:UIControlStateNormal];
        }
            break;
```

**Comment by ZhipingYang** [comment]
在UUMessageFrame预计算size的时候，记得也需要转换文案计算size

https://github.com/ZhipingYang/UUChatTableView/blob/master/Class/UUMessageFrame.m#L44

**Comment by xiaobeifeng** [comment]
嗯嗯，这个是表情cell的显示问题。我在发送图片后图片上带文字这个问题还是没有得到解决。。。

**Comment by xiaobeifeng** [comment]
发送完图片之后，我一滚动列表，就会出现图片上出现其他cell上的文字的问题

**Comment by ZhipingYang** [comment]
那就是cell复用问题了啊，这个demo可能还有不严谨的地方。😬

https://github.com/ZhipingYang/UUChatTableView/blob/master/Class/UUMessageCell.m#L181

这个地方, 设置title是错误的，应该是AttributeTitle
```
    switch (message.type) {
        case UUMessageTypeText:
            [self.btnContent setTitle:message.strContent forState:UIControlStateNormal];
            break;
        case UUMessageTypePicture:
        {
            self.btnContent.backImageView.hidden = NO;
            self.btnContent.backImageView.image = message.picture;
            self.btnContent.backImageView.frame = CGRectMake(0, 0, self.btnContent.frame.size.width, self.btnContent.frame.size.height);
            [self makeMaskView:self.btnContent.backImageView withImage:normal];
        }
```

**Comment by xiaobeifeng** [comment]
title这个问题我更改过来了
```
 case UUMessageTypeText:
        {
            NSMutableAttributedString *attributedMessage = [[NSMutableAttributedString alloc] initWithString:message.strContent attributes:@{ NSFontAttributeName: [UIFont systemFontOfSize:14.0], NSForegroundColorAttributeName: [UIColor grayColor] }];
            [PPStickerDataManager.sharedInstance replaceEmojiForAttributedString:attributedMessage font:[UIFont systemFontOfSize:14.0]];
            
            [self.btnContent setAttributedTitle:attributedMessage forState:UIControlStateNormal];
//            [self.btnContent setTitle:message.strContent forState:UIControlStateNormal];
        }
            break;
```

您可以在我出现这个问题提供个思路吗？我只要一设置按钮文字为富文本就会出现上述问题，用纯文本就没有问题

**Comment by ZhipingYang** [comment]
这个demo主要提供一个思路，还有很多功能没有完善。。。哈哈哈，所以也没有做成 CocoaPods，问题解决了，就close吧

**Comment by xiaobeifeng** [comment]
UUMessageCell中

下面的btnContent 这样写  cell的显示就会出现问题，这个问题我还是没想通，可以帮忙解答下怎么处理吗？
[self.btnContent setAttributedTitle:attributedMessage forState:UIControlStateNormal];


switch (message.type) {
        case UUMessageTypeText:
        {


    // 这样写cell显示就没有问题
            [self.btnContent setTitle:message.strContent forState:UIControlStateNormal];
        }
            break;

**Comment by ZhipingYang** [comment]
UILabel的text和attributeText是两个不同的属性，不显示需要需要两个都置空。最简单的做法就是在cell的prepareForReuse 方法中恢复cell的初始状态

**Comment by xiaobeifeng** [comment]
已经解决了，感谢帮助

在 2018年10月25日，上午11:31，XcodeYang <notifications@github.com<mailto:notifications@github.com>> 写道：


UILabel的text和attributeText是两个不同的属性，不显示需要需要两个都置空。最简单的做法就是在cell的prepareForReuse 方法中恢复cell的初始状态
